validation:
  password: "^(?=.*[0-9!\\\"#$%&'()*+,-./:;<=>?@ ^ _`\\[\\\\\\]])(?=.*[a-z])(?=.*[A-Z])(?=\\S+$).{12,}$"
  minAge: 18

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect